# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19f7077f634fd6dd091099e0288ad455dc00e866b94b078400e04faea99d5492b33a4da8c15c889058bd43d922e96336f51bcc5742f2398f9641e4c662af0831

test:
  secret_key_base: 99b41d007c9ef44f92760ac54c1f46c61ebc6ee22037f8223b4a2be3b5b9bf0ffaed3f56457c4b479b1f841325a640fc16eeb4103fb5da980b88542a60b9733f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
